FROM node:18-alpine

WORKDIR /app

# Copy package files
COPY package.json ./

# Install dependencies
RUN npm install

# Copy application files
COPY . .

# Expose next.js port
EXPOSE 3000

ENV PORT=3000

# Start development server (or npm run build && npm run start for production)
CMD ["npm", "run", "dev"]
